// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repositoryIMPL

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TAvaliaco struct {
	ID        int32
	UsuarioID int32
	ProdutoID pgtype.Int4
	JogoID    pgtype.Int4
	Nota      pgtype.Int4
	Avaliacao pgtype.Text
}

type TFavorito struct {
	ID        int32
	UsuarioID int32
	ProdutoID pgtype.Int4
	JogoID    pgtype.Int4
}

type TJogo struct {
	ID        int32
	Nome      string
	Sinopse   pgtype.Text
	Avaliacao pgtype.Int4
	Genero    pgtype.Text
}

type TParametro struct {
	ID        int32
	Nome      pgtype.Text
	Descricao pgtype.Text
	Valor     pgtype.Text
}

type TPerfi struct {
	ID                    int32
	Nome                  string
	Descricao             string
	Ativo                 pgtype.Bool
	DataUltimaAtualizacao pgtype.Timestamp
}

type TPerfilPermissao struct {
	ID          int32
	PerfilID    int32
	PermissaoID int32
	DataHora    pgtype.Timestamp
}

type TPermisso struct {
	ID                    int32
	Nome                  string
	Descricao             string
	Ativo                 pgtype.Bool
	DataUltimaAtualizacao pgtype.Timestamp
}

type TProduto struct {
	ID        int32
	Nome      string
	Descricao pgtype.Text
	Avaliacao pgtype.Int4
	Genero    pgtype.Text
}

type TUsuario struct {
	ID                    int32
	Nome                  string
	Email                 string
	Senha                 string
	Ativo                 pgtype.Bool
	TokenResetSenha       pgtype.Text
	DataUltimaAtualizacao pgtype.Timestamp
	SenhaAtualizada       pgtype.Bool
}

type TUsuarioJogo struct {
	ID        int32
	UsuarioID int32
	JogoID    int32
	DataHora  pgtype.Timestamp
}

type TUsuarioPerfil struct {
	ID        int32
	UsuarioID int32
	PerfilID  int32
	DataHora  pgtype.Timestamp
}
