// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: permissoes.sql

package repositoryIMPL

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermissao = `-- name: CreatePermissao :one
INSERT INTO t_permissoes (nome, descricao, ativo, data_ultima_atualizacao)
VALUES ($1, $2, $3, $4) 
RETURNING id, nome, descricao, ativo, data_ultima_atualizacao
`

type CreatePermissaoParams struct {
	Nome                  string
	Descricao             string
	Ativo                 pgtype.Bool
	DataUltimaAtualizacao pgtype.Timestamp
}

func (q *Queries) CreatePermissao(ctx context.Context, arg CreatePermissaoParams) (TPermisso, error) {
	row := q.db.QueryRow(ctx, createPermissao,
		arg.Nome,
		arg.Descricao,
		arg.Ativo,
		arg.DataUltimaAtualizacao,
	)
	var i TPermisso
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.Ativo,
		&i.DataUltimaAtualizacao,
	)
	return i, err
}

const findAllPermissoes = `-- name: FindAllPermissoes :many
SELECT id, nome, descricao, ativo, data_ultima_atualizacao FROM t_permissoes
`

func (q *Queries) FindAllPermissoes(ctx context.Context) ([]TPermisso, error) {
	rows, err := q.db.Query(ctx, findAllPermissoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TPermisso
	for rows.Next() {
		var i TPermisso
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Descricao,
			&i.Ativo,
			&i.DataUltimaAtualizacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findPermissaoByID = `-- name: FindPermissaoByID :one
SELECT id, nome, descricao, ativo, data_ultima_atualizacao FROM t_permissoes WHERE id = $1
`

func (q *Queries) FindPermissaoByID(ctx context.Context, id int32) (TPermisso, error) {
	row := q.db.QueryRow(ctx, findPermissaoByID, id)
	var i TPermisso
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.Ativo,
		&i.DataUltimaAtualizacao,
	)
	return i, err
}

const findPermissaoByNome = `-- name: FindPermissaoByNome :one
SELECT id, nome, descricao, ativo, data_ultima_atualizacao FROM t_permissoes WHERE nome = $1
`

func (q *Queries) FindPermissaoByNome(ctx context.Context, nome string) (TPermisso, error) {
	row := q.db.QueryRow(ctx, findPermissaoByNome, nome)
	var i TPermisso
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.Ativo,
		&i.DataUltimaAtualizacao,
	)
	return i, err
}

const updatePermissao = `-- name: UpdatePermissao :one
UPDATE t_permissoes 
SET nome = $1, descricao = $2, ativo = $3, data_ultima_atualizacao = $4
WHERE id = $5
RETURNING id, nome, descricao, ativo, data_ultima_atualizacao
`

type UpdatePermissaoParams struct {
	Nome                  string
	Descricao             string
	Ativo                 pgtype.Bool
	DataUltimaAtualizacao pgtype.Timestamp
	ID                    int32
}

func (q *Queries) UpdatePermissao(ctx context.Context, arg UpdatePermissaoParams) (TPermisso, error) {
	row := q.db.QueryRow(ctx, updatePermissao,
		arg.Nome,
		arg.Descricao,
		arg.Ativo,
		arg.DataUltimaAtualizacao,
		arg.ID,
	)
	var i TPermisso
	err := row.Scan(
		&i.ID,
		&i.Nome,
		&i.Descricao,
		&i.Ativo,
		&i.DataUltimaAtualizacao,
	)
	return i, err
}
