// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: avaliacoes.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Avaliacoes_FindAllAvaliacoes_FullMethodName      = "/grpc.Avaliacoes/FindAllAvaliacoes"
	Avaliacoes_FindAvaliacaoById_FullMethodName      = "/grpc.Avaliacoes/FindAvaliacaoById"
	Avaliacoes_FindAvaliacaoByUsuario_FullMethodName = "/grpc.Avaliacoes/FindAvaliacaoByUsuario"
	Avaliacoes_FindAvaliacaoByProduto_FullMethodName = "/grpc.Avaliacoes/FindAvaliacaoByProduto"
	Avaliacoes_FindAvaliacaoByJogo_FullMethodName    = "/grpc.Avaliacoes/FindAvaliacaoByJogo"
	Avaliacoes_CreateAvaliacao_FullMethodName        = "/grpc.Avaliacoes/CreateAvaliacao"
	Avaliacoes_UpdateAvaliacao_FullMethodName        = "/grpc.Avaliacoes/UpdateAvaliacao"
	Avaliacoes_DeleteAvaliacao_FullMethodName        = "/grpc.Avaliacoes/DeleteAvaliacao"
)

// AvaliacoesClient is the client API for Avaliacoes service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Definição do serviço
type AvaliacoesClient interface {
	FindAllAvaliacoes(ctx context.Context, in *RequestVazio, opts ...grpc.CallOption) (*ListaAvaliacoes, error)
	FindAvaliacaoById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Avaliacao, error)
	FindAvaliacaoByUsuario(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ListaAvaliacoes, error)
	FindAvaliacaoByProduto(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ListaAvaliacoes, error)
	FindAvaliacaoByJogo(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ListaAvaliacoes, error)
	CreateAvaliacao(ctx context.Context, in *Avaliacao, opts ...grpc.CallOption) (*Avaliacao, error)
	UpdateAvaliacao(ctx context.Context, in *Avaliacao, opts ...grpc.CallOption) (*Avaliacao, error)
	DeleteAvaliacao(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ResponseBool, error)
}

type avaliacoesClient struct {
	cc grpc.ClientConnInterface
}

func NewAvaliacoesClient(cc grpc.ClientConnInterface) AvaliacoesClient {
	return &avaliacoesClient{cc}
}

func (c *avaliacoesClient) FindAllAvaliacoes(ctx context.Context, in *RequestVazio, opts ...grpc.CallOption) (*ListaAvaliacoes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaAvaliacoes)
	err := c.cc.Invoke(ctx, Avaliacoes_FindAllAvaliacoes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avaliacoesClient) FindAvaliacaoById(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*Avaliacao, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Avaliacao)
	err := c.cc.Invoke(ctx, Avaliacoes_FindAvaliacaoById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avaliacoesClient) FindAvaliacaoByUsuario(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ListaAvaliacoes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaAvaliacoes)
	err := c.cc.Invoke(ctx, Avaliacoes_FindAvaliacaoByUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avaliacoesClient) FindAvaliacaoByProduto(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ListaAvaliacoes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaAvaliacoes)
	err := c.cc.Invoke(ctx, Avaliacoes_FindAvaliacaoByProduto_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avaliacoesClient) FindAvaliacaoByJogo(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ListaAvaliacoes, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListaAvaliacoes)
	err := c.cc.Invoke(ctx, Avaliacoes_FindAvaliacaoByJogo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avaliacoesClient) CreateAvaliacao(ctx context.Context, in *Avaliacao, opts ...grpc.CallOption) (*Avaliacao, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Avaliacao)
	err := c.cc.Invoke(ctx, Avaliacoes_CreateAvaliacao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avaliacoesClient) UpdateAvaliacao(ctx context.Context, in *Avaliacao, opts ...grpc.CallOption) (*Avaliacao, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Avaliacao)
	err := c.cc.Invoke(ctx, Avaliacoes_UpdateAvaliacao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *avaliacoesClient) DeleteAvaliacao(ctx context.Context, in *RequestId, opts ...grpc.CallOption) (*ResponseBool, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseBool)
	err := c.cc.Invoke(ctx, Avaliacoes_DeleteAvaliacao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AvaliacoesServer is the server API for Avaliacoes service.
// All implementations must embed UnimplementedAvaliacoesServer
// for forward compatibility.
//
// Definição do serviço
type AvaliacoesServer interface {
	FindAllAvaliacoes(context.Context, *RequestVazio) (*ListaAvaliacoes, error)
	FindAvaliacaoById(context.Context, *RequestId) (*Avaliacao, error)
	FindAvaliacaoByUsuario(context.Context, *RequestId) (*ListaAvaliacoes, error)
	FindAvaliacaoByProduto(context.Context, *RequestId) (*ListaAvaliacoes, error)
	FindAvaliacaoByJogo(context.Context, *RequestId) (*ListaAvaliacoes, error)
	CreateAvaliacao(context.Context, *Avaliacao) (*Avaliacao, error)
	UpdateAvaliacao(context.Context, *Avaliacao) (*Avaliacao, error)
	DeleteAvaliacao(context.Context, *RequestId) (*ResponseBool, error)
	mustEmbedUnimplementedAvaliacoesServer()
}

// UnimplementedAvaliacoesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAvaliacoesServer struct{}

func (UnimplementedAvaliacoesServer) FindAllAvaliacoes(context.Context, *RequestVazio) (*ListaAvaliacoes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAllAvaliacoes not implemented")
}
func (UnimplementedAvaliacoesServer) FindAvaliacaoById(context.Context, *RequestId) (*Avaliacao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAvaliacaoById not implemented")
}
func (UnimplementedAvaliacoesServer) FindAvaliacaoByUsuario(context.Context, *RequestId) (*ListaAvaliacoes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAvaliacaoByUsuario not implemented")
}
func (UnimplementedAvaliacoesServer) FindAvaliacaoByProduto(context.Context, *RequestId) (*ListaAvaliacoes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAvaliacaoByProduto not implemented")
}
func (UnimplementedAvaliacoesServer) FindAvaliacaoByJogo(context.Context, *RequestId) (*ListaAvaliacoes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAvaliacaoByJogo not implemented")
}
func (UnimplementedAvaliacoesServer) CreateAvaliacao(context.Context, *Avaliacao) (*Avaliacao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAvaliacao not implemented")
}
func (UnimplementedAvaliacoesServer) UpdateAvaliacao(context.Context, *Avaliacao) (*Avaliacao, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAvaliacao not implemented")
}
func (UnimplementedAvaliacoesServer) DeleteAvaliacao(context.Context, *RequestId) (*ResponseBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAvaliacao not implemented")
}
func (UnimplementedAvaliacoesServer) mustEmbedUnimplementedAvaliacoesServer() {}
func (UnimplementedAvaliacoesServer) testEmbeddedByValue()                    {}

// UnsafeAvaliacoesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AvaliacoesServer will
// result in compilation errors.
type UnsafeAvaliacoesServer interface {
	mustEmbedUnimplementedAvaliacoesServer()
}

func RegisterAvaliacoesServer(s grpc.ServiceRegistrar, srv AvaliacoesServer) {
	// If the following call pancis, it indicates UnimplementedAvaliacoesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Avaliacoes_ServiceDesc, srv)
}

func _Avaliacoes_FindAllAvaliacoes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVazio)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).FindAllAvaliacoes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_FindAllAvaliacoes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).FindAllAvaliacoes(ctx, req.(*RequestVazio))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avaliacoes_FindAvaliacaoById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).FindAvaliacaoById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_FindAvaliacaoById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).FindAvaliacaoById(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avaliacoes_FindAvaliacaoByUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).FindAvaliacaoByUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_FindAvaliacaoByUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).FindAvaliacaoByUsuario(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avaliacoes_FindAvaliacaoByProduto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).FindAvaliacaoByProduto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_FindAvaliacaoByProduto_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).FindAvaliacaoByProduto(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avaliacoes_FindAvaliacaoByJogo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).FindAvaliacaoByJogo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_FindAvaliacaoByJogo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).FindAvaliacaoByJogo(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avaliacoes_CreateAvaliacao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Avaliacao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).CreateAvaliacao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_CreateAvaliacao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).CreateAvaliacao(ctx, req.(*Avaliacao))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avaliacoes_UpdateAvaliacao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Avaliacao)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).UpdateAvaliacao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_UpdateAvaliacao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).UpdateAvaliacao(ctx, req.(*Avaliacao))
	}
	return interceptor(ctx, in, info, handler)
}

func _Avaliacoes_DeleteAvaliacao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AvaliacoesServer).DeleteAvaliacao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Avaliacoes_DeleteAvaliacao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AvaliacoesServer).DeleteAvaliacao(ctx, req.(*RequestId))
	}
	return interceptor(ctx, in, info, handler)
}

// Avaliacoes_ServiceDesc is the grpc.ServiceDesc for Avaliacoes service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Avaliacoes_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc.Avaliacoes",
	HandlerType: (*AvaliacoesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllAvaliacoes",
			Handler:    _Avaliacoes_FindAllAvaliacoes_Handler,
		},
		{
			MethodName: "FindAvaliacaoById",
			Handler:    _Avaliacoes_FindAvaliacaoById_Handler,
		},
		{
			MethodName: "FindAvaliacaoByUsuario",
			Handler:    _Avaliacoes_FindAvaliacaoByUsuario_Handler,
		},
		{
			MethodName: "FindAvaliacaoByProduto",
			Handler:    _Avaliacoes_FindAvaliacaoByProduto_Handler,
		},
		{
			MethodName: "FindAvaliacaoByJogo",
			Handler:    _Avaliacoes_FindAvaliacaoByJogo_Handler,
		},
		{
			MethodName: "CreateAvaliacao",
			Handler:    _Avaliacoes_CreateAvaliacao_Handler,
		},
		{
			MethodName: "UpdateAvaliacao",
			Handler:    _Avaliacoes_UpdateAvaliacao_Handler,
		},
		{
			MethodName: "DeleteAvaliacao",
			Handler:    _Avaliacoes_DeleteAvaliacao_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "avaliacoes.proto",
}
