// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.25.1
// source: modelos.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Definição do modelo de Jogo
type Jogo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome      string  `protobuf:"bytes,3,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Sinopse   string  `protobuf:"bytes,4,opt,name=Sinopse,proto3" json:"Sinopse,omitempty"`
	Avaliacao float64 `protobuf:"fixed64,5,opt,name=Avaliacao,proto3" json:"Avaliacao,omitempty"`
	Genero    string  `protobuf:"bytes,6,opt,name=Genero,proto3" json:"Genero,omitempty"`
}

func (x *Jogo) Reset() {
	*x = Jogo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Jogo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Jogo) ProtoMessage() {}

func (x *Jogo) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Jogo.ProtoReflect.Descriptor instead.
func (*Jogo) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{0}
}

func (x *Jogo) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Jogo) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Jogo) GetSinopse() string {
	if x != nil {
		return x.Sinopse
	}
	return ""
}

func (x *Jogo) GetAvaliacao() float64 {
	if x != nil {
		return x.Avaliacao
	}
	return 0
}

func (x *Jogo) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

// Definição do modelo de Produto
type Produto struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome      string  `protobuf:"bytes,3,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Descricao string  `protobuf:"bytes,4,opt,name=Descricao,proto3" json:"Descricao,omitempty"`
	Avaliacao float64 `protobuf:"fixed64,5,opt,name=Avaliacao,proto3" json:"Avaliacao,omitempty"`
	Genero    string  `protobuf:"bytes,6,opt,name=Genero,proto3" json:"Genero,omitempty"`
}

func (x *Produto) Reset() {
	*x = Produto{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Produto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Produto) ProtoMessage() {}

func (x *Produto) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Produto.ProtoReflect.Descriptor instead.
func (*Produto) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{1}
}

func (x *Produto) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Produto) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Produto) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Produto) GetAvaliacao() float64 {
	if x != nil {
		return x.Avaliacao
	}
	return 0
}

func (x *Produto) GetGenero() string {
	if x != nil {
		return x.Genero
	}
	return ""
}

// Definição do modelo de Avaliação
type Avaliacao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID        int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Usuario   *Usuario `protobuf:"bytes,2,opt,name=Usuario,proto3" json:"Usuario,omitempty"`
	Produto   *Produto `protobuf:"bytes,3,opt,name=Produto,proto3" json:"Produto,omitempty"`
	Jogo      *Jogo    `protobuf:"bytes,4,opt,name=Jogo,proto3" json:"Jogo,omitempty"`
	Nota      int32    `protobuf:"varint,5,opt,name=Nota,proto3" json:"Nota,omitempty"`
	Avaliacao string   `protobuf:"bytes,6,opt,name=Avaliacao,proto3" json:"Avaliacao,omitempty"`
}

func (x *Avaliacao) Reset() {
	*x = Avaliacao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Avaliacao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Avaliacao) ProtoMessage() {}

func (x *Avaliacao) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Avaliacao.ProtoReflect.Descriptor instead.
func (*Avaliacao) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{2}
}

func (x *Avaliacao) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Avaliacao) GetUsuario() *Usuario {
	if x != nil {
		return x.Usuario
	}
	return nil
}

func (x *Avaliacao) GetProduto() *Produto {
	if x != nil {
		return x.Produto
	}
	return nil
}

func (x *Avaliacao) GetJogo() *Jogo {
	if x != nil {
		return x.Jogo
	}
	return nil
}

func (x *Avaliacao) GetNota() int32 {
	if x != nil {
		return x.Nota
	}
	return 0
}

func (x *Avaliacao) GetAvaliacao() string {
	if x != nil {
		return x.Avaliacao
	}
	return ""
}

// Definição do modelo de Favoritos
type Favorito struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID      int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Usuario *Usuario `protobuf:"bytes,2,opt,name=Usuario,proto3" json:"Usuario,omitempty"`
	Produto *Produto `protobuf:"bytes,3,opt,name=Produto,proto3" json:"Produto,omitempty"`
	Jogo    *Jogo    `protobuf:"bytes,4,opt,name=Jogo,proto3" json:"Jogo,omitempty"`
}

func (x *Favorito) Reset() {
	*x = Favorito{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Favorito) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Favorito) ProtoMessage() {}

func (x *Favorito) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Favorito.ProtoReflect.Descriptor instead.
func (*Favorito) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{3}
}

func (x *Favorito) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Favorito) GetUsuario() *Usuario {
	if x != nil {
		return x.Usuario
	}
	return nil
}

func (x *Favorito) GetProduto() *Produto {
	if x != nil {
		return x.Produto
	}
	return nil
}

func (x *Favorito) GetJogo() *Jogo {
	if x != nil {
		return x.Jogo
	}
	return nil
}

// Definição do modelo de Perfis
type Perfil struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                    int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome                  string `protobuf:"bytes,2,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Descricao             string `protobuf:"bytes,3,opt,name=Descricao,proto3" json:"Descricao,omitempty"`
	Ativo                 bool   `protobuf:"varint,4,opt,name=Ativo,proto3" json:"Ativo,omitempty"`
	DataUltimaAtualizacao string `protobuf:"bytes,5,opt,name=DataUltimaAtualizacao,proto3" json:"DataUltimaAtualizacao,omitempty"`
}

func (x *Perfil) Reset() {
	*x = Perfil{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Perfil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Perfil) ProtoMessage() {}

func (x *Perfil) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Perfil.ProtoReflect.Descriptor instead.
func (*Perfil) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{4}
}

func (x *Perfil) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Perfil) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Perfil) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Perfil) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *Perfil) GetDataUltimaAtualizacao() string {
	if x != nil {
		return x.DataUltimaAtualizacao
	}
	return ""
}

// Definição do modelo de Permissões
type Permissao struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                    int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome                  string `protobuf:"bytes,2,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Descricao             string `protobuf:"bytes,3,opt,name=Descricao,proto3" json:"Descricao,omitempty"`
	Ativo                 bool   `protobuf:"varint,4,opt,name=Ativo,proto3" json:"Ativo,omitempty"`
	DataUltimaAtualizacao string `protobuf:"bytes,5,opt,name=DataUltimaAtualizacao,proto3" json:"DataUltimaAtualizacao,omitempty"`
}

func (x *Permissao) Reset() {
	*x = Permissao{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Permissao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Permissao) ProtoMessage() {}

func (x *Permissao) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Permissao.ProtoReflect.Descriptor instead.
func (*Permissao) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{5}
}

func (x *Permissao) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Permissao) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Permissao) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Permissao) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *Permissao) GetDataUltimaAtualizacao() string {
	if x != nil {
		return x.DataUltimaAtualizacao
	}
	return ""
}

// Definição do modelo de relação entre Perfil e Permissões
type PerfilPermissoes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perfil     *Perfil      `protobuf:"bytes,1,opt,name=perfil,proto3" json:"perfil,omitempty"`
	Permissoes []*Permissao `protobuf:"bytes,2,rep,name=permissoes,proto3" json:"permissoes,omitempty"`
}

func (x *PerfilPermissoes) Reset() {
	*x = PerfilPermissoes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfilPermissoes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfilPermissoes) ProtoMessage() {}

func (x *PerfilPermissoes) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfilPermissoes.ProtoReflect.Descriptor instead.
func (*PerfilPermissoes) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{6}
}

func (x *PerfilPermissoes) GetPerfil() *Perfil {
	if x != nil {
		return x.Perfil
	}
	return nil
}

func (x *PerfilPermissoes) GetPermissoes() []*Permissao {
	if x != nil {
		return x.Permissoes
	}
	return nil
}

// Definição do modelo de Usuario
type Usuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID                    int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome                  string `protobuf:"bytes,2,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Email                 string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Senha                 string `protobuf:"bytes,4,opt,name=Senha,proto3" json:"Senha,omitempty"`
	Ativo                 bool   `protobuf:"varint,5,opt,name=Ativo,proto3" json:"Ativo,omitempty"`
	TokenResetSenha       string `protobuf:"bytes,6,opt,name=TokenResetSenha,proto3" json:"TokenResetSenha,omitempty"`
	DataUltimaAtualizacao string `protobuf:"bytes,7,opt,name=DataUltimaAtualizacao,proto3" json:"DataUltimaAtualizacao,omitempty"`
	SenhaAtualizada       bool   `protobuf:"varint,8,opt,name=SenhaAtualizada,proto3" json:"SenhaAtualizada,omitempty"`
}

func (x *Usuario) Reset() {
	*x = Usuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Usuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usuario) ProtoMessage() {}

func (x *Usuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usuario.ProtoReflect.Descriptor instead.
func (*Usuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{7}
}

func (x *Usuario) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Usuario) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Usuario) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Usuario) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

func (x *Usuario) GetAtivo() bool {
	if x != nil {
		return x.Ativo
	}
	return false
}

func (x *Usuario) GetTokenResetSenha() string {
	if x != nil {
		return x.TokenResetSenha
	}
	return ""
}

func (x *Usuario) GetDataUltimaAtualizacao() string {
	if x != nil {
		return x.DataUltimaAtualizacao
	}
	return ""
}

func (x *Usuario) GetSenhaAtualizada() bool {
	if x != nil {
		return x.SenhaAtualizada
	}
	return false
}

// Definição do modelo de relação entre Usuário e Perfis
type UsuarioPerfis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Usuario *Usuario  `protobuf:"bytes,1,opt,name=usuario,proto3" json:"usuario,omitempty"`
	Perfis  []*Perfil `protobuf:"bytes,2,rep,name=perfis,proto3" json:"perfis,omitempty"`
}

func (x *UsuarioPerfis) Reset() {
	*x = UsuarioPerfis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsuarioPerfis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsuarioPerfis) ProtoMessage() {}

func (x *UsuarioPerfis) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsuarioPerfis.ProtoReflect.Descriptor instead.
func (*UsuarioPerfis) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{8}
}

func (x *UsuarioPerfis) GetUsuario() *Usuario {
	if x != nil {
		return x.Usuario
	}
	return nil
}

func (x *UsuarioPerfis) GetPerfis() []*Perfil {
	if x != nil {
		return x.Perfis
	}
	return nil
}

// Definição do modelo de relação entre Perfil e Usuários
type PerfilUsuarios struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Perfil   *Perfil    `protobuf:"bytes,1,opt,name=perfil,proto3" json:"perfil,omitempty"`
	Usuarios []*Usuario `protobuf:"bytes,2,rep,name=usuarios,proto3" json:"usuarios,omitempty"`
}

func (x *PerfilUsuarios) Reset() {
	*x = PerfilUsuarios{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PerfilUsuarios) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PerfilUsuarios) ProtoMessage() {}

func (x *PerfilUsuarios) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PerfilUsuarios.ProtoReflect.Descriptor instead.
func (*PerfilUsuarios) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{9}
}

func (x *PerfilUsuarios) GetPerfil() *Perfil {
	if x != nil {
		return x.Perfil
	}
	return nil
}

func (x *PerfilUsuarios) GetUsuarios() []*Usuario {
	if x != nil {
		return x.Usuarios
	}
	return nil
}

type Parametro struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nome      string `protobuf:"bytes,2,opt,name=nome,proto3" json:"nome,omitempty"`
	Descricao string `protobuf:"bytes,3,opt,name=descricao,proto3" json:"descricao,omitempty"`
	Valor     string `protobuf:"bytes,4,opt,name=valor,proto3" json:"valor,omitempty"`
}

func (x *Parametro) Reset() {
	*x = Parametro{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parametro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parametro) ProtoMessage() {}

func (x *Parametro) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parametro.ProtoReflect.Descriptor instead.
func (*Parametro) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{10}
}

func (x *Parametro) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Parametro) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *Parametro) GetDescricao() string {
	if x != nil {
		return x.Descricao
	}
	return ""
}

func (x *Parametro) GetValor() string {
	if x != nil {
		return x.Valor
	}
	return ""
}

// Definição do modelo de envio de e-mail para reset de Senha
type EmailReset struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
}

func (x *EmailReset) Reset() {
	*x = EmailReset{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailReset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailReset) ProtoMessage() {}

func (x *EmailReset) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailReset.ProtoReflect.Descriptor instead.
func (*EmailReset) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{11}
}

func (x *EmailReset) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

// Definição do modelo de Login dos usuários
type LoginUsuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Senha string `protobuf:"bytes,2,opt,name=Senha,proto3" json:"Senha,omitempty"`
}

func (x *LoginUsuario) Reset() {
	*x = LoginUsuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginUsuario) ProtoMessage() {}

func (x *LoginUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginUsuario.ProtoReflect.Descriptor instead.
func (*LoginUsuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{12}
}

func (x *LoginUsuario) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginUsuario) GetSenha() string {
	if x != nil {
		return x.Senha
	}
	return ""
}

// Definição do modelo de retorno da requisição de Login
type RetornoLoginUsuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID    int32  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Nome  string `protobuf:"bytes,2,opt,name=Nome,proto3" json:"Nome,omitempty"`
	Email string `protobuf:"bytes,3,opt,name=Email,proto3" json:"Email,omitempty"`
	Token string `protobuf:"bytes,4,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *RetornoLoginUsuario) Reset() {
	*x = RetornoLoginUsuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RetornoLoginUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetornoLoginUsuario) ProtoMessage() {}

func (x *RetornoLoginUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetornoLoginUsuario.ProtoReflect.Descriptor instead.
func (*RetornoLoginUsuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{13}
}

func (x *RetornoLoginUsuario) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *RetornoLoginUsuario) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

func (x *RetornoLoginUsuario) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RetornoLoginUsuario) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ResetSenhaUsuario struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	SenhaNova string `protobuf:"bytes,2,opt,name=SenhaNova,proto3" json:"SenhaNova,omitempty"`
}

func (x *ResetSenhaUsuario) Reset() {
	*x = ResetSenhaUsuario{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetSenhaUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetSenhaUsuario) ProtoMessage() {}

func (x *ResetSenhaUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetSenhaUsuario.ProtoReflect.Descriptor instead.
func (*ResetSenhaUsuario) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{14}
}

func (x *ResetSenhaUsuario) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResetSenhaUsuario) GetSenhaNova() string {
	if x != nil {
		return x.SenhaNova
	}
	return ""
}

type RequestVazio struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RequestVazio) Reset() {
	*x = RequestVazio{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestVazio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVazio) ProtoMessage() {}

func (x *RequestVazio) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVazio.ProtoReflect.Descriptor instead.
func (*RequestVazio) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{15}
}

type RequestId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int32 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *RequestId) Reset() {
	*x = RequestId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestId) ProtoMessage() {}

func (x *RequestId) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestId.ProtoReflect.Descriptor instead.
func (*RequestId) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{16}
}

func (x *RequestId) GetID() int32 {
	if x != nil {
		return x.ID
	}
	return 0
}

type ResponseBool struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alterado bool `protobuf:"varint,1,opt,name=alterado,proto3" json:"alterado,omitempty"`
}

func (x *ResponseBool) Reset() {
	*x = ResponseBool{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseBool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseBool) ProtoMessage() {}

func (x *ResponseBool) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseBool.ProtoReflect.Descriptor instead.
func (*ResponseBool) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{17}
}

func (x *ResponseBool) GetAlterado() bool {
	if x != nil {
		return x.Alterado
	}
	return false
}

type RequestNome struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nome string `protobuf:"bytes,1,opt,name=Nome,proto3" json:"Nome,omitempty"`
}

func (x *RequestNome) Reset() {
	*x = RequestNome{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestNome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNome) ProtoMessage() {}

func (x *RequestNome) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNome.ProtoReflect.Descriptor instead.
func (*RequestNome) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{18}
}

func (x *RequestNome) GetNome() string {
	if x != nil {
		return x.Nome
	}
	return ""
}

type RequestUsuarioId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UsuarioId int32 `protobuf:"varint,1,opt,name=UsuarioId,proto3" json:"UsuarioId,omitempty"`
}

func (x *RequestUsuarioId) Reset() {
	*x = RequestUsuarioId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUsuarioId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUsuarioId) ProtoMessage() {}

func (x *RequestUsuarioId) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUsuarioId.ProtoReflect.Descriptor instead.
func (*RequestUsuarioId) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{19}
}

func (x *RequestUsuarioId) GetUsuarioId() int32 {
	if x != nil {
		return x.UsuarioId
	}
	return 0
}

type RequestProdutoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProdutoId int32 `protobuf:"varint,1,opt,name=ProdutoId,proto3" json:"ProdutoId,omitempty"`
}

func (x *RequestProdutoId) Reset() {
	*x = RequestProdutoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestProdutoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProdutoId) ProtoMessage() {}

func (x *RequestProdutoId) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProdutoId.ProtoReflect.Descriptor instead.
func (*RequestProdutoId) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{20}
}

func (x *RequestProdutoId) GetProdutoId() int32 {
	if x != nil {
		return x.ProdutoId
	}
	return 0
}

type RequestJogoId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JogoId int32 `protobuf:"varint,1,opt,name=JogoId,proto3" json:"JogoId,omitempty"`
}

func (x *RequestJogoId) Reset() {
	*x = RequestJogoId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_modelos_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestJogoId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestJogoId) ProtoMessage() {}

func (x *RequestJogoId) ProtoReflect() protoreflect.Message {
	mi := &file_modelos_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestJogoId.ProtoReflect.Descriptor instead.
func (*RequestJogoId) Descriptor() ([]byte, []int) {
	return file_modelos_proto_rawDescGZIP(), []int{21}
}

func (x *RequestJogoId) GetJogoId() int32 {
	if x != nil {
		return x.JogoId
	}
	return 0
}

var File_modelos_proto protoreflect.FileDescriptor

var file_modelos_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x6f, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x04, 0x67, 0x72, 0x70, 0x63, 0x22, 0x7a, 0x0a, 0x04, 0x4a, 0x6f, 0x67, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x69, 0x6e, 0x6f, 0x70, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x53, 0x69, 0x6e, 0x6f, 0x70, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x41,
	0x76, 0x61, 0x6c, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x09,
	0x41, 0x76, 0x61, 0x6c, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x47, 0x65, 0x6e,
	0x65, 0x72, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65, 0x6e, 0x65, 0x72,
	0x6f, 0x22, 0x81, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x12,
	0x1c, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x6c, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x09, 0x41, 0x76, 0x61, 0x6c, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x16, 0x0a,
	0x06, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47,
	0x65, 0x6e, 0x65, 0x72, 0x6f, 0x22, 0xbf, 0x01, 0x0a, 0x09, 0x41, 0x76, 0x61, 0x6c, 0x69, 0x61,
	0x63, 0x61, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x49, 0x44, 0x12, 0x27, 0x0a, 0x07, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x52, 0x07, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x27, 0x0a, 0x07,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x52, 0x07, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x04, 0x4a, 0x6f, 0x67, 0x6f, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x67, 0x6f, 0x52,
	0x04, 0x4a, 0x6f, 0x67, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x74, 0x61, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x4e, 0x6f, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x41, 0x76, 0x61,
	0x6c, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x41, 0x76,
	0x61, 0x6c, 0x69, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x8c, 0x01, 0x0a, 0x08, 0x46, 0x61, 0x76, 0x6f,
	0x72, 0x69, 0x74, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x49, 0x44, 0x12, 0x27, 0x0a, 0x07, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x75,
	0x61, 0x72, 0x69, 0x6f, 0x52, 0x07, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x27, 0x0a,
	0x07, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x52, 0x07, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x12, 0x1e, 0x0a, 0x04, 0x4a, 0x6f, 0x67, 0x6f, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x4a, 0x6f, 0x67, 0x6f,
	0x52, 0x04, 0x4a, 0x6f, 0x67, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x06, 0x50, 0x65, 0x72, 0x66, 0x69,
	0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63,
	0x61, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x63, 0x61, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x05, 0x41, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x34, 0x0a, 0x15, 0x44, 0x61, 0x74,
	0x61, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63,
	0x61, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6c,
	0x74, 0x69, 0x6d, 0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x22,
	0x99, 0x01, 0x0a, 0x09, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x61, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x6f, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x63, 0x61, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x41, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05,
	0x41, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x34, 0x0a, 0x15, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6c, 0x74,
	0x69, 0x6d, 0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x15, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x61,
	0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x22, 0x69, 0x0a, 0x10, 0x50,
	0x65, 0x72, 0x66, 0x69, 0x6c, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x12,
	0x24, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x06, 0x70,
	0x65, 0x72, 0x66, 0x69, 0x6c, 0x12, 0x2f, 0x0a, 0x0a, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73,
	0x6f, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x67, 0x72, 0x70, 0x63,
	0x2e, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x61, 0x6f, 0x52, 0x0a, 0x70, 0x65, 0x72, 0x6d,
	0x69, 0x73, 0x73, 0x6f, 0x65, 0x73, 0x22, 0xf9, 0x01, 0x0a, 0x07, 0x55, 0x73, 0x75, 0x61, 0x72,
	0x69, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05,
	0x53, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x65, 0x6e,
	0x68, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x41, 0x74, 0x69, 0x76, 0x6f, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x41, 0x74, 0x69, 0x76, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e,
	0x68, 0x61, 0x12, 0x34, 0x0a, 0x15, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x61,
	0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x15, 0x44, 0x61, 0x74, 0x61, 0x55, 0x6c, 0x74, 0x69, 0x6d, 0x61, 0x41, 0x74, 0x75,
	0x61, 0x6c, 0x69, 0x7a, 0x61, 0x63, 0x61, 0x6f, 0x12, 0x28, 0x0a, 0x0f, 0x53, 0x65, 0x6e, 0x68,
	0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x64, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0f, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x41, 0x74, 0x75, 0x61, 0x6c, 0x69, 0x7a, 0x61,
	0x64, 0x61, 0x22, 0x5e, 0x0a, 0x0d, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x50, 0x65, 0x72,
	0x66, 0x69, 0x73, 0x12, 0x27, 0x0a, 0x07, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x52, 0x07, 0x75, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x24, 0x0a, 0x06,
	0x70, 0x65, 0x72, 0x66, 0x69, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x52, 0x06, 0x70, 0x65, 0x72, 0x66,
	0x69, 0x73, 0x22, 0x61, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x55, 0x73, 0x75, 0x61,
	0x72, 0x69, 0x6f, 0x73, 0x12, 0x24, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x50, 0x65, 0x72, 0x66,
	0x69, 0x6c, 0x52, 0x06, 0x70, 0x65, 0x72, 0x66, 0x69, 0x6c, 0x12, 0x29, 0x0a, 0x08, 0x75, 0x73,
	0x75, 0x61, 0x72, 0x69, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x67,
	0x72, 0x70, 0x63, 0x2e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x75,
	0x61, 0x72, 0x69, 0x6f, 0x73, 0x22, 0x63, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x72, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x6f, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x63, 0x61, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x65, 0x73, 0x63, 0x72,
	0x69, 0x63, 0x61, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x6f, 0x72, 0x22, 0x22, 0x0a, 0x0a, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x3a,
	0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x22, 0x65, 0x0a, 0x13, 0x52, 0x65,
	0x74, 0x6f, 0x72, 0x6e, 0x6f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69,
	0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x49,
	0x44, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x47, 0x0a, 0x11, 0x52, 0x65, 0x73, 0x65, 0x74, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x55,
	0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1c, 0x0a, 0x09,
	0x53, 0x65, 0x6e, 0x68, 0x61, 0x4e, 0x6f, 0x76, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x53, 0x65, 0x6e, 0x68, 0x61, 0x4e, 0x6f, 0x76, 0x61, 0x22, 0x0e, 0x0a, 0x0c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x56, 0x61, 0x7a, 0x69, 0x6f, 0x22, 0x1b, 0x0a, 0x09, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x49, 0x44, 0x22, 0x2a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x6f, 0x6f, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x6c, 0x74, 0x65, 0x72,
	0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x61, 0x6c, 0x74, 0x65, 0x72,
	0x61, 0x64, 0x6f, 0x22, 0x21, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4e, 0x6f,
	0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x6f, 0x6d, 0x65, 0x22, 0x30, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x55, 0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x73,
	0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x55,
	0x73, 0x75, 0x61, 0x72, 0x69, 0x6f, 0x49, 0x64, 0x22, 0x30, 0x0a, 0x10, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x74, 0x6f, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x4a, 0x6f, 0x67, 0x6f, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x4a,
	0x6f, 0x67, 0x6f, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x4a, 0x6f, 0x67,
	0x6f, 0x49, 0x64, 0x42, 0x14, 0x5a, 0x12, 0x70, 0x69, 0x78, 0x65, 0x6c, 0x6e, 0x65, 0x73, 0x74,
	0x2f, 0x61, 0x70, 0x70, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_modelos_proto_rawDescOnce sync.Once
	file_modelos_proto_rawDescData = file_modelos_proto_rawDesc
)

func file_modelos_proto_rawDescGZIP() []byte {
	file_modelos_proto_rawDescOnce.Do(func() {
		file_modelos_proto_rawDescData = protoimpl.X.CompressGZIP(file_modelos_proto_rawDescData)
	})
	return file_modelos_proto_rawDescData
}

var file_modelos_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_modelos_proto_goTypes = []any{
	(*Jogo)(nil),                // 0: grpc.Jogo
	(*Produto)(nil),             // 1: grpc.Produto
	(*Avaliacao)(nil),           // 2: grpc.Avaliacao
	(*Favorito)(nil),            // 3: grpc.Favorito
	(*Perfil)(nil),              // 4: grpc.Perfil
	(*Permissao)(nil),           // 5: grpc.Permissao
	(*PerfilPermissoes)(nil),    // 6: grpc.PerfilPermissoes
	(*Usuario)(nil),             // 7: grpc.Usuario
	(*UsuarioPerfis)(nil),       // 8: grpc.UsuarioPerfis
	(*PerfilUsuarios)(nil),      // 9: grpc.PerfilUsuarios
	(*Parametro)(nil),           // 10: grpc.Parametro
	(*EmailReset)(nil),          // 11: grpc.EmailReset
	(*LoginUsuario)(nil),        // 12: grpc.LoginUsuario
	(*RetornoLoginUsuario)(nil), // 13: grpc.RetornoLoginUsuario
	(*ResetSenhaUsuario)(nil),   // 14: grpc.ResetSenhaUsuario
	(*RequestVazio)(nil),        // 15: grpc.RequestVazio
	(*RequestId)(nil),           // 16: grpc.RequestId
	(*ResponseBool)(nil),        // 17: grpc.ResponseBool
	(*RequestNome)(nil),         // 18: grpc.RequestNome
	(*RequestUsuarioId)(nil),    // 19: grpc.RequestUsuarioId
	(*RequestProdutoId)(nil),    // 20: grpc.RequestProdutoId
	(*RequestJogoId)(nil),       // 21: grpc.RequestJogoId
}
var file_modelos_proto_depIdxs = []int32{
	7,  // 0: grpc.Avaliacao.Usuario:type_name -> grpc.Usuario
	1,  // 1: grpc.Avaliacao.Produto:type_name -> grpc.Produto
	0,  // 2: grpc.Avaliacao.Jogo:type_name -> grpc.Jogo
	7,  // 3: grpc.Favorito.Usuario:type_name -> grpc.Usuario
	1,  // 4: grpc.Favorito.Produto:type_name -> grpc.Produto
	0,  // 5: grpc.Favorito.Jogo:type_name -> grpc.Jogo
	4,  // 6: grpc.PerfilPermissoes.perfil:type_name -> grpc.Perfil
	5,  // 7: grpc.PerfilPermissoes.permissoes:type_name -> grpc.Permissao
	7,  // 8: grpc.UsuarioPerfis.usuario:type_name -> grpc.Usuario
	4,  // 9: grpc.UsuarioPerfis.perfis:type_name -> grpc.Perfil
	4,  // 10: grpc.PerfilUsuarios.perfil:type_name -> grpc.Perfil
	7,  // 11: grpc.PerfilUsuarios.usuarios:type_name -> grpc.Usuario
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_modelos_proto_init() }
func file_modelos_proto_init() {
	if File_modelos_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_modelos_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Jogo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Produto); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*Avaliacao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Favorito); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Perfil); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Permissao); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*PerfilPermissoes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Usuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*UsuarioPerfis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*PerfilUsuarios); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Parametro); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*EmailReset); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*LoginUsuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*RetornoLoginUsuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*ResetSenhaUsuario); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*RequestVazio); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*RequestId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*ResponseBool); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*RequestNome); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*RequestUsuarioId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*RequestProdutoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_modelos_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*RequestJogoId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_modelos_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_modelos_proto_goTypes,
		DependencyIndexes: file_modelos_proto_depIdxs,
		MessageInfos:      file_modelos_proto_msgTypes,
	}.Build()
	File_modelos_proto = out.File
	file_modelos_proto_rawDesc = nil
	file_modelos_proto_goTypes = nil
	file_modelos_proto_depIdxs = nil
}
